kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: helm-tiller-manager
  namespace: helm-tiller
rules:
- apiGroups: ["", "batch", "extensions", "apps"]
  resources: ["*"]
  verbs: ["*"]
