kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: helm-tiller-binding
  namespace: helm-tiller
subjects:
- kind: ServiceAccount
  name: helm-tiller
  namespace: helm-tiller
roleRef:
  kind: Role
  name: helm-tiller-manager
  apiGroup: rbac.authorization.k8s.io
